# dvc.yaml
stages:
  collect_data:
    cmd: python src/main.py
    deps:
      - src/main.py
      - src/yahoo_finance_collector.py
      - src/data_validator.py
      - src/data_preprocessing_module.py
    outs:
      - data/raw:
          persist: true
      - data/validation:
          persist: true
      - data/processed:
          persist: true