stages:
  collect_data:
    cmd: python src/main.py
    deps:
      - src/main.py
      - src/yahoo_finance_collector.py
    outs:
      - data/

## uncomment the following after validator is reviewed and updated:
  # validate_data:
  #   cmd: python src/data_validator.py
  #   deps:
  #     - data/
  #     - src/data_validator.py
  #   outs:
  #     - data/validation_report.json